#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uniandes.AccesoDatos.Menu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aspnetdb")]
	public partial class AccesoDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPERFIL_OPERACION(PERFIL_OPERACION instance);
    partial void UpdatePERFIL_OPERACION(PERFIL_OPERACION instance);
    partial void DeletePERFIL_OPERACION(PERFIL_OPERACION instance);
    partial void InsertPERFIL(PERFIL instance);
    partial void UpdatePERFIL(PERFIL instance);
    partial void DeletePERFIL(PERFIL instance);
    partial void InsertOPERACION(OPERACION instance);
    partial void UpdateOPERACION(OPERACION instance);
    partial void DeleteOPERACION(OPERACION instance);
    partial void Insertaspnet_Users(aspnet_Users instance);
    partial void Updateaspnet_Users(aspnet_Users instance);
    partial void Deleteaspnet_Users(aspnet_Users instance);
    partial void Insertaspnet_UsersInRoles(aspnet_UsersInRoles instance);
    partial void Updateaspnet_UsersInRoles(aspnet_UsersInRoles instance);
    partial void Deleteaspnet_UsersInRoles(aspnet_UsersInRoles instance);
    partial void Insertaspnet_Roles(aspnet_Roles instance);
    partial void Updateaspnet_Roles(aspnet_Roles instance);
    partial void Deleteaspnet_Roles(aspnet_Roles instance);
    partial void InsertPreguntasSecreta(PreguntasSecreta instance);
    partial void UpdatePreguntasSecreta(PreguntasSecreta instance);
    partial void DeletePreguntasSecreta(PreguntasSecreta instance);
    partial void InsertActivity(Activity instance);
    partial void UpdateActivity(Activity instance);
    partial void DeleteActivity(Activity instance);
    #endregion
		
		public AccesoDatosDataContext() : 
				base(global::Uniandes.AccesoDatos.Menu.Properties.Settings.Default.aspnetdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PERFIL_OPERACION> PERFIL_OPERACION
		{
			get
			{
				return this.GetTable<PERFIL_OPERACION>();
			}
		}
		
		public System.Data.Linq.Table<PERFIL> PERFIL
		{
			get
			{
				return this.GetTable<PERFIL>();
			}
		}
		
		public System.Data.Linq.Table<OPERACION> OPERACION
		{
			get
			{
				return this.GetTable<OPERACION>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_Users> aspnet_Users
		{
			get
			{
				return this.GetTable<aspnet_Users>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_UsersInRoles> aspnet_UsersInRoles
		{
			get
			{
				return this.GetTable<aspnet_UsersInRoles>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_Roles> aspnet_Roles
		{
			get
			{
				return this.GetTable<aspnet_Roles>();
			}
		}
		
		public System.Data.Linq.Table<PreguntasSecreta> PreguntasSecreta
		{
			get
			{
				return this.GetTable<PreguntasSecreta>();
			}
		}
		
		public System.Data.Linq.Table<Activity> Activity
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERFIL_OPERACION")]
	public partial class PERFIL_OPERACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PERFIL_OPERACION;
		
		private System.Nullable<int> _ID_PERFIL;
		
		private System.Nullable<System.Guid> _RoleId;
		
		private System.Nullable<int> _ID_OPERACION;
		
		private EntityRef<PERFIL> _PERFIL;
		
		private EntityRef<OPERACION> _OPERACION;
		
		private EntityRef<aspnet_Roles> _aspnet_Roles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PERFIL_OPERACIONChanging(int value);
    partial void OnID_PERFIL_OPERACIONChanged();
    partial void OnID_PERFILChanging(System.Nullable<int> value);
    partial void OnID_PERFILChanged();
    partial void OnRoleIdChanging(System.Nullable<System.Guid> value);
    partial void OnRoleIdChanged();
    partial void OnID_OPERACIONChanging(System.Nullable<int> value);
    partial void OnID_OPERACIONChanged();
    #endregion
		
		public PERFIL_OPERACION()
		{
			this._PERFIL = default(EntityRef<PERFIL>);
			this._OPERACION = default(EntityRef<OPERACION>);
			this._aspnet_Roles = default(EntityRef<aspnet_Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERFIL_OPERACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PERFIL_OPERACION
		{
			get
			{
				return this._ID_PERFIL_OPERACION;
			}
			set
			{
				if ((this._ID_PERFIL_OPERACION != value))
				{
					this.OnID_PERFIL_OPERACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_PERFIL_OPERACION = value;
					this.SendPropertyChanged("ID_PERFIL_OPERACION");
					this.OnID_PERFIL_OPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERFIL", DbType="Int")]
		public System.Nullable<int> ID_PERFIL
		{
			get
			{
				return this._ID_PERFIL;
			}
			set
			{
				if ((this._ID_PERFIL != value))
				{
					if (this._PERFIL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PERFILChanging(value);
					this.SendPropertyChanging();
					this._ID_PERFIL = value;
					this.SendPropertyChanged("ID_PERFIL");
					this.OnID_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					if (this._aspnet_Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OPERACION", DbType="Int")]
		public System.Nullable<int> ID_OPERACION
		{
			get
			{
				return this._ID_OPERACION;
			}
			set
			{
				if ((this._ID_OPERACION != value))
				{
					if (this._OPERACION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_OPERACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_OPERACION = value;
					this.SendPropertyChanged("ID_OPERACION");
					this.OnID_OPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERFIL_PERFIL_OPERACION", Storage="_PERFIL", ThisKey="ID_PERFIL", OtherKey="ID_PERFIL", IsForeignKey=true)]
		public PERFIL PERFIL
		{
			get
			{
				return this._PERFIL.Entity;
			}
			set
			{
				PERFIL previousValue = this._PERFIL.Entity;
				if (((previousValue != value) 
							|| (this._PERFIL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PERFIL.Entity = null;
						previousValue.PERFIL_OPERACION.Remove(this);
					}
					this._PERFIL.Entity = value;
					if ((value != null))
					{
						value.PERFIL_OPERACION.Add(this);
						this._ID_PERFIL = value.ID_PERFIL;
					}
					else
					{
						this._ID_PERFIL = default(Nullable<int>);
					}
					this.SendPropertyChanged("PERFIL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OPERACION_PERFIL_OPERACION", Storage="_OPERACION", ThisKey="ID_OPERACION", OtherKey="ID_OPERACION", IsForeignKey=true)]
		public OPERACION OPERACION
		{
			get
			{
				return this._OPERACION.Entity;
			}
			set
			{
				OPERACION previousValue = this._OPERACION.Entity;
				if (((previousValue != value) 
							|| (this._OPERACION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OPERACION.Entity = null;
						previousValue.PERFIL_OPERACION.Remove(this);
					}
					this._OPERACION.Entity = value;
					if ((value != null))
					{
						value.PERFIL_OPERACION.Add(this);
						this._ID_OPERACION = value.ID_OPERACION;
					}
					else
					{
						this._ID_OPERACION = default(Nullable<int>);
					}
					this.SendPropertyChanged("OPERACION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Roles_PERFIL_OPERACION", Storage="_aspnet_Roles", ThisKey="RoleId", OtherKey="RoleId", IsForeignKey=true)]
		public aspnet_Roles aspnet_Roles
		{
			get
			{
				return this._aspnet_Roles.Entity;
			}
			set
			{
				aspnet_Roles previousValue = this._aspnet_Roles.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Roles.Entity = null;
						previousValue.PERFIL_OPERACION.Remove(this);
					}
					this._aspnet_Roles.Entity = value;
					if ((value != null))
					{
						value.PERFIL_OPERACION.Add(this);
						this._RoleId = value.RoleId;
					}
					else
					{
						this._RoleId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("aspnet_Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERFIL")]
	public partial class PERFIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PERFIL;
		
		private string _NOMBRE_PERFIL;
		
		private string _DESCRIPCION;
		
		private string _PREFIJO;
		
		private EntitySet<PERFIL_OPERACION> _PERFIL_OPERACION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PERFILChanging(int value);
    partial void OnID_PERFILChanged();
    partial void OnNOMBRE_PERFILChanging(string value);
    partial void OnNOMBRE_PERFILChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnPREFIJOChanging(string value);
    partial void OnPREFIJOChanged();
    #endregion
		
		public PERFIL()
		{
			this._PERFIL_OPERACION = new EntitySet<PERFIL_OPERACION>(new Action<PERFIL_OPERACION>(this.attach_PERFIL_OPERACION), new Action<PERFIL_OPERACION>(this.detach_PERFIL_OPERACION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PERFIL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PERFIL
		{
			get
			{
				return this._ID_PERFIL;
			}
			set
			{
				if ((this._ID_PERFIL != value))
				{
					this.OnID_PERFILChanging(value);
					this.SendPropertyChanging();
					this._ID_PERFIL = value;
					this.SendPropertyChanged("ID_PERFIL");
					this.OnID_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PERFIL", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string NOMBRE_PERFIL
		{
			get
			{
				return this._NOMBRE_PERFIL;
			}
			set
			{
				if ((this._NOMBRE_PERFIL != value))
				{
					this.OnNOMBRE_PERFILChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_PERFIL = value;
					this.SendPropertyChanged("NOMBRE_PERFIL");
					this.OnNOMBRE_PERFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREFIJO", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string PREFIJO
		{
			get
			{
				return this._PREFIJO;
			}
			set
			{
				if ((this._PREFIJO != value))
				{
					this.OnPREFIJOChanging(value);
					this.SendPropertyChanging();
					this._PREFIJO = value;
					this.SendPropertyChanged("PREFIJO");
					this.OnPREFIJOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PERFIL_PERFIL_OPERACION", Storage="_PERFIL_OPERACION", ThisKey="ID_PERFIL", OtherKey="ID_PERFIL")]
		public EntitySet<PERFIL_OPERACION> PERFIL_OPERACION
		{
			get
			{
				return this._PERFIL_OPERACION;
			}
			set
			{
				this._PERFIL_OPERACION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.PERFIL = this;
		}
		
		private void detach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.PERFIL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OPERACION")]
	public partial class OPERACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_OPERACION;
		
		private System.Nullable<int> _ID_OPERACION_PADRE;
		
		private string _NOMBRE;
		
		private string _URL;
		
		private string _VISIBLE_MENU;
		
		private EntitySet<PERFIL_OPERACION> _PERFIL_OPERACION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_OPERACIONChanging(int value);
    partial void OnID_OPERACIONChanged();
    partial void OnID_OPERACION_PADREChanging(System.Nullable<int> value);
    partial void OnID_OPERACION_PADREChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnVISIBLE_MENUChanging(string value);
    partial void OnVISIBLE_MENUChanged();
    #endregion
		
		public OPERACION()
		{
			this._PERFIL_OPERACION = new EntitySet<PERFIL_OPERACION>(new Action<PERFIL_OPERACION>(this.attach_PERFIL_OPERACION), new Action<PERFIL_OPERACION>(this.detach_PERFIL_OPERACION));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OPERACION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_OPERACION
		{
			get
			{
				return this._ID_OPERACION;
			}
			set
			{
				if ((this._ID_OPERACION != value))
				{
					this.OnID_OPERACIONChanging(value);
					this.SendPropertyChanging();
					this._ID_OPERACION = value;
					this.SendPropertyChanged("ID_OPERACION");
					this.OnID_OPERACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_OPERACION_PADRE", DbType="Int")]
		public System.Nullable<int> ID_OPERACION_PADRE
		{
			get
			{
				return this._ID_OPERACION_PADRE;
			}
			set
			{
				if ((this._ID_OPERACION_PADRE != value))
				{
					this.OnID_OPERACION_PADREChanging(value);
					this.SendPropertyChanging();
					this._ID_OPERACION_PADRE = value;
					this.SendPropertyChanged("ID_OPERACION_PADRE");
					this.OnID_OPERACION_PADREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(500)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(500)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISIBLE_MENU", DbType="VarChar(500)")]
		public string VISIBLE_MENU
		{
			get
			{
				return this._VISIBLE_MENU;
			}
			set
			{
				if ((this._VISIBLE_MENU != value))
				{
					this.OnVISIBLE_MENUChanging(value);
					this.SendPropertyChanging();
					this._VISIBLE_MENU = value;
					this.SendPropertyChanged("VISIBLE_MENU");
					this.OnVISIBLE_MENUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OPERACION_PERFIL_OPERACION", Storage="_PERFIL_OPERACION", ThisKey="ID_OPERACION", OtherKey="ID_OPERACION")]
		public EntitySet<PERFIL_OPERACION> PERFIL_OPERACION
		{
			get
			{
				return this._PERFIL_OPERACION;
			}
			set
			{
				this._PERFIL_OPERACION.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.OPERACION = this;
		}
		
		private void detach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.OPERACION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
	public partial class aspnet_Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _LoweredUserName;
		
		private string _MobileAlias;
		
		private bool _IsAnonymous;
		
		private System.DateTime _LastActivityDate;
		
		private EntitySet<aspnet_UsersInRoles> _aspnet_UsersInRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
		
		public aspnet_Users()
		{
			this._aspnet_UsersInRoles = new EntitySet<aspnet_UsersInRoles>(new Action<aspnet_UsersInRoles>(this.attach_aspnet_UsersInRoles), new Action<aspnet_UsersInRoles>(this.detach_aspnet_UsersInRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				if ((this._LoweredUserName != value))
				{
					this.OnLoweredUserNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredUserName = value;
					this.SendPropertyChanged("LoweredUserName");
					this.OnLoweredUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
		public string MobileAlias
		{
			get
			{
				return this._MobileAlias;
			}
			set
			{
				if ((this._MobileAlias != value))
				{
					this.OnMobileAliasChanging(value);
					this.SendPropertyChanging();
					this._MobileAlias = value;
					this.SendPropertyChanged("MobileAlias");
					this.OnMobileAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
		public bool IsAnonymous
		{
			get
			{
				return this._IsAnonymous;
			}
			set
			{
				if ((this._IsAnonymous != value))
				{
					this.OnIsAnonymousChanging(value);
					this.SendPropertyChanging();
					this._IsAnonymous = value;
					this.SendPropertyChanged("IsAnonymous");
					this.OnIsAnonymousChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Users_aspnet_UsersInRoles", Storage="_aspnet_UsersInRoles", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<aspnet_UsersInRoles> aspnet_UsersInRoles
		{
			get
			{
				return this._aspnet_UsersInRoles;
			}
			set
			{
				this._aspnet_UsersInRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_aspnet_UsersInRoles(aspnet_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Users = this;
		}
		
		private void detach_aspnet_UsersInRoles(aspnet_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_UsersInRoles")]
	public partial class aspnet_UsersInRoles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private System.Guid _RoleId;
		
		private EntityRef<aspnet_Users> _aspnet_Users;
		
		private EntityRef<aspnet_Roles> _aspnet_Roles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    #endregion
		
		public aspnet_UsersInRoles()
		{
			this._aspnet_Users = default(EntityRef<aspnet_Users>);
			this._aspnet_Roles = default(EntityRef<aspnet_Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._aspnet_Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					if (this._aspnet_Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Users_aspnet_UsersInRoles", Storage="_aspnet_Users", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public aspnet_Users aspnet_Users
		{
			get
			{
				return this._aspnet_Users.Entity;
			}
			set
			{
				aspnet_Users previousValue = this._aspnet_Users.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Users.Entity = null;
						previousValue.aspnet_UsersInRoles.Remove(this);
					}
					this._aspnet_Users.Entity = value;
					if ((value != null))
					{
						value.aspnet_UsersInRoles.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("aspnet_Users");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Roles_aspnet_UsersInRoles", Storage="_aspnet_Roles", ThisKey="RoleId", OtherKey="RoleId", IsForeignKey=true)]
		public aspnet_Roles aspnet_Roles
		{
			get
			{
				return this._aspnet_Roles.Entity;
			}
			set
			{
				aspnet_Roles previousValue = this._aspnet_Roles.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Roles.Entity = null;
						previousValue.aspnet_UsersInRoles.Remove(this);
					}
					this._aspnet_Roles.Entity = value;
					if ((value != null))
					{
						value.aspnet_UsersInRoles.Add(this);
						this._RoleId = value.RoleId;
					}
					else
					{
						this._RoleId = default(System.Guid);
					}
					this.SendPropertyChanged("aspnet_Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Roles")]
	public partial class aspnet_Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _RoleId;
		
		private string _RoleName;
		
		private string _LoweredRoleName;
		
		private string _Description;
		
		private EntitySet<PERFIL_OPERACION> _PERFIL_OPERACION;
		
		private EntitySet<aspnet_UsersInRoles> _aspnet_UsersInRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnLoweredRoleNameChanging(string value);
    partial void OnLoweredRoleNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public aspnet_Roles()
		{
			this._PERFIL_OPERACION = new EntitySet<PERFIL_OPERACION>(new Action<PERFIL_OPERACION>(this.attach_PERFIL_OPERACION), new Action<PERFIL_OPERACION>(this.detach_PERFIL_OPERACION));
			this._aspnet_UsersInRoles = new EntitySet<aspnet_UsersInRoles>(new Action<aspnet_UsersInRoles>(this.attach_aspnet_UsersInRoles), new Action<aspnet_UsersInRoles>(this.detach_aspnet_UsersInRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredRoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredRoleName
		{
			get
			{
				return this._LoweredRoleName;
			}
			set
			{
				if ((this._LoweredRoleName != value))
				{
					this.OnLoweredRoleNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredRoleName = value;
					this.SendPropertyChanged("LoweredRoleName");
					this.OnLoweredRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Roles_PERFIL_OPERACION", Storage="_PERFIL_OPERACION", ThisKey="RoleId", OtherKey="RoleId")]
		public EntitySet<PERFIL_OPERACION> PERFIL_OPERACION
		{
			get
			{
				return this._PERFIL_OPERACION;
			}
			set
			{
				this._PERFIL_OPERACION.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Roles_aspnet_UsersInRoles", Storage="_aspnet_UsersInRoles", ThisKey="RoleId", OtherKey="RoleId")]
		public EntitySet<aspnet_UsersInRoles> aspnet_UsersInRoles
		{
			get
			{
				return this._aspnet_UsersInRoles;
			}
			set
			{
				this._aspnet_UsersInRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Roles = this;
		}
		
		private void detach_PERFIL_OPERACION(PERFIL_OPERACION entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Roles = null;
		}
		
		private void attach_aspnet_UsersInRoles(aspnet_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Roles = this;
		}
		
		private void detach_aspnet_UsersInRoles(aspnet_UsersInRoles entity)
		{
			this.SendPropertyChanging();
			entity.aspnet_Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PreguntasSecreta")]
	public partial class PreguntasSecreta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pregunta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpreguntaChanging(string value);
    partial void OnpreguntaChanged();
    #endregion
		
		public PreguntasSecreta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pregunta", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string pregunta
		{
			get
			{
				return this._pregunta;
			}
			set
			{
				if ((this._pregunta != value))
				{
					this.OnpreguntaChanging(value);
					this.SendPropertyChanging();
					this._pregunta = value;
					this.SendPropertyChanged("pregunta");
					this.OnpreguntaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activity")]
	public partial class Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Activity_Id;
		
		private System.Guid _UserId;
		
		private int _Id_Operacion;
		
		private System.DateTime _ActivityDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnActivity_IdChanging(long value);
    partial void OnActivity_IdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnId_OperacionChanging(int value);
    partial void OnId_OperacionChanged();
    partial void OnActivityDayChanging(System.DateTime value);
    partial void OnActivityDayChanged();
    #endregion
		
		public Activity()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activity_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Activity_Id
		{
			get
			{
				return this._Activity_Id;
			}
			set
			{
				if ((this._Activity_Id != value))
				{
					this.OnActivity_IdChanging(value);
					this.SendPropertyChanging();
					this._Activity_Id = value;
					this.SendPropertyChanged("Activity_Id");
					this.OnActivity_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Operacion", DbType="Int NOT NULL")]
		public int Id_Operacion
		{
			get
			{
				return this._Id_Operacion;
			}
			set
			{
				if ((this._Id_Operacion != value))
				{
					this.OnId_OperacionChanging(value);
					this.SendPropertyChanging();
					this._Id_Operacion = value;
					this.SendPropertyChanged("Id_Operacion");
					this.OnId_OperacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityDay", DbType="DateTime NOT NULL")]
		public System.DateTime ActivityDay
		{
			get
			{
				return this._ActivityDay;
			}
			set
			{
				if ((this._ActivityDay != value))
				{
					this.OnActivityDayChanging(value);
					this.SendPropertyChanging();
					this._ActivityDay = value;
					this.SendPropertyChanged("ActivityDay");
					this.OnActivityDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
